//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/network_classes_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkClasses_List_FullMethodName   = "/osac.private.v1.NetworkClasses/List"
	NetworkClasses_Get_FullMethodName    = "/osac.private.v1.NetworkClasses/Get"
	NetworkClasses_Create_FullMethodName = "/osac.private.v1.NetworkClasses/Create"
	NetworkClasses_Update_FullMethodName = "/osac.private.v1.NetworkClasses/Update"
	NetworkClasses_Delete_FullMethodName = "/osac.private.v1.NetworkClasses/Delete"
	NetworkClasses_Signal_FullMethodName = "/osac.private.v1.NetworkClasses/Signal"
)

// NetworkClassesClient is the client API for NetworkClasses service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkClassesClient interface {
	// Retrieves the list of network classes.
	List(ctx context.Context, in *NetworkClassesListRequest, opts ...grpc.CallOption) (*NetworkClassesListResponse, error)
	// Retrieves the details of one specific network class.
	Get(ctx context.Context, in *NetworkClassesGetRequest, opts ...grpc.CallOption) (*NetworkClassesGetResponse, error)
	// Creates a new network class.
	Create(ctx context.Context, in *NetworkClassesCreateRequest, opts ...grpc.CallOption) (*NetworkClassesCreateResponse, error)
	// Updates an existing network class.
	Update(ctx context.Context, in *NetworkClassesUpdateRequest, opts ...grpc.CallOption) (*NetworkClassesUpdateResponse, error)
	// Deletes a network class.
	Delete(ctx context.Context, in *NetworkClassesDeleteRequest, opts ...grpc.CallOption) (*NetworkClassesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *NetworkClassesSignalRequest, opts ...grpc.CallOption) (*NetworkClassesSignalResponse, error)
}

type networkClassesClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkClassesClient(cc grpc.ClientConnInterface) NetworkClassesClient {
	return &networkClassesClient{cc}
}

func (c *networkClassesClient) List(ctx context.Context, in *NetworkClassesListRequest, opts ...grpc.CallOption) (*NetworkClassesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkClassesListResponse)
	err := c.cc.Invoke(ctx, NetworkClasses_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClassesClient) Get(ctx context.Context, in *NetworkClassesGetRequest, opts ...grpc.CallOption) (*NetworkClassesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkClassesGetResponse)
	err := c.cc.Invoke(ctx, NetworkClasses_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClassesClient) Create(ctx context.Context, in *NetworkClassesCreateRequest, opts ...grpc.CallOption) (*NetworkClassesCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkClassesCreateResponse)
	err := c.cc.Invoke(ctx, NetworkClasses_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClassesClient) Update(ctx context.Context, in *NetworkClassesUpdateRequest, opts ...grpc.CallOption) (*NetworkClassesUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkClassesUpdateResponse)
	err := c.cc.Invoke(ctx, NetworkClasses_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClassesClient) Delete(ctx context.Context, in *NetworkClassesDeleteRequest, opts ...grpc.CallOption) (*NetworkClassesDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkClassesDeleteResponse)
	err := c.cc.Invoke(ctx, NetworkClasses_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkClassesClient) Signal(ctx context.Context, in *NetworkClassesSignalRequest, opts ...grpc.CallOption) (*NetworkClassesSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkClassesSignalResponse)
	err := c.cc.Invoke(ctx, NetworkClasses_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkClassesServer is the server API for NetworkClasses service.
// All implementations must embed UnimplementedNetworkClassesServer
// for forward compatibility.
type NetworkClassesServer interface {
	// Retrieves the list of network classes.
	List(context.Context, *NetworkClassesListRequest) (*NetworkClassesListResponse, error)
	// Retrieves the details of one specific network class.
	Get(context.Context, *NetworkClassesGetRequest) (*NetworkClassesGetResponse, error)
	// Creates a new network class.
	Create(context.Context, *NetworkClassesCreateRequest) (*NetworkClassesCreateResponse, error)
	// Updates an existing network class.
	Update(context.Context, *NetworkClassesUpdateRequest) (*NetworkClassesUpdateResponse, error)
	// Deletes a network class.
	Delete(context.Context, *NetworkClassesDeleteRequest) (*NetworkClassesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *NetworkClassesSignalRequest) (*NetworkClassesSignalResponse, error)
	mustEmbedUnimplementedNetworkClassesServer()
}

// UnimplementedNetworkClassesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkClassesServer struct{}

func (UnimplementedNetworkClassesServer) List(context.Context, *NetworkClassesListRequest) (*NetworkClassesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNetworkClassesServer) Get(context.Context, *NetworkClassesGetRequest) (*NetworkClassesGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedNetworkClassesServer) Create(context.Context, *NetworkClassesCreateRequest) (*NetworkClassesCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedNetworkClassesServer) Update(context.Context, *NetworkClassesUpdateRequest) (*NetworkClassesUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedNetworkClassesServer) Delete(context.Context, *NetworkClassesDeleteRequest) (*NetworkClassesDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedNetworkClassesServer) Signal(context.Context, *NetworkClassesSignalRequest) (*NetworkClassesSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedNetworkClassesServer) mustEmbedUnimplementedNetworkClassesServer() {}
func (UnimplementedNetworkClassesServer) testEmbeddedByValue()                        {}

// UnsafeNetworkClassesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkClassesServer will
// result in compilation errors.
type UnsafeNetworkClassesServer interface {
	mustEmbedUnimplementedNetworkClassesServer()
}

func RegisterNetworkClassesServer(s grpc.ServiceRegistrar, srv NetworkClassesServer) {
	// If the following call pancis, it indicates UnimplementedNetworkClassesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkClasses_ServiceDesc, srv)
}

func _NetworkClasses_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkClassesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkClassesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkClasses_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkClassesServer).List(ctx, req.(*NetworkClassesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkClasses_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkClassesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkClassesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkClasses_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkClassesServer).Get(ctx, req.(*NetworkClassesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkClasses_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkClassesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkClassesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkClasses_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkClassesServer).Create(ctx, req.(*NetworkClassesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkClasses_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkClassesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkClassesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkClasses_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkClassesServer).Update(ctx, req.(*NetworkClassesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkClasses_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkClassesDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkClassesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkClasses_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkClassesServer).Delete(ctx, req.(*NetworkClassesDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkClasses_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkClassesSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkClassesServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkClasses_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkClassesServer).Signal(ctx, req.(*NetworkClassesSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkClasses_ServiceDesc is the grpc.ServiceDesc for NetworkClasses service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkClasses_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.NetworkClasses",
	HandlerType: (*NetworkClassesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _NetworkClasses_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _NetworkClasses_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _NetworkClasses_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _NetworkClasses_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NetworkClasses_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _NetworkClasses_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/network_classes_service.proto",
}
