//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/security_groups_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityGroups_List_FullMethodName   = "/osac.private.v1.SecurityGroups/List"
	SecurityGroups_Get_FullMethodName    = "/osac.private.v1.SecurityGroups/Get"
	SecurityGroups_Create_FullMethodName = "/osac.private.v1.SecurityGroups/Create"
	SecurityGroups_Update_FullMethodName = "/osac.private.v1.SecurityGroups/Update"
	SecurityGroups_Delete_FullMethodName = "/osac.private.v1.SecurityGroups/Delete"
	SecurityGroups_Signal_FullMethodName = "/osac.private.v1.SecurityGroups/Signal"
)

// SecurityGroupsClient is the client API for SecurityGroups service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityGroupsClient interface {
	// Retrieves the list of security groups.
	List(ctx context.Context, in *SecurityGroupsListRequest, opts ...grpc.CallOption) (*SecurityGroupsListResponse, error)
	// Retrieves the details of one specific security group.
	Get(ctx context.Context, in *SecurityGroupsGetRequest, opts ...grpc.CallOption) (*SecurityGroupsGetResponse, error)
	// Creates a new security group.
	Create(ctx context.Context, in *SecurityGroupsCreateRequest, opts ...grpc.CallOption) (*SecurityGroupsCreateResponse, error)
	// Updates an existing security group.
	Update(ctx context.Context, in *SecurityGroupsUpdateRequest, opts ...grpc.CallOption) (*SecurityGroupsUpdateResponse, error)
	// Deletes a security group.
	Delete(ctx context.Context, in *SecurityGroupsDeleteRequest, opts ...grpc.CallOption) (*SecurityGroupsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *SecurityGroupsSignalRequest, opts ...grpc.CallOption) (*SecurityGroupsSignalResponse, error)
}

type securityGroupsClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityGroupsClient(cc grpc.ClientConnInterface) SecurityGroupsClient {
	return &securityGroupsClient{cc}
}

func (c *securityGroupsClient) List(ctx context.Context, in *SecurityGroupsListRequest, opts ...grpc.CallOption) (*SecurityGroupsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityGroupsListResponse)
	err := c.cc.Invoke(ctx, SecurityGroups_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityGroupsClient) Get(ctx context.Context, in *SecurityGroupsGetRequest, opts ...grpc.CallOption) (*SecurityGroupsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityGroupsGetResponse)
	err := c.cc.Invoke(ctx, SecurityGroups_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityGroupsClient) Create(ctx context.Context, in *SecurityGroupsCreateRequest, opts ...grpc.CallOption) (*SecurityGroupsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityGroupsCreateResponse)
	err := c.cc.Invoke(ctx, SecurityGroups_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityGroupsClient) Update(ctx context.Context, in *SecurityGroupsUpdateRequest, opts ...grpc.CallOption) (*SecurityGroupsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityGroupsUpdateResponse)
	err := c.cc.Invoke(ctx, SecurityGroups_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityGroupsClient) Delete(ctx context.Context, in *SecurityGroupsDeleteRequest, opts ...grpc.CallOption) (*SecurityGroupsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityGroupsDeleteResponse)
	err := c.cc.Invoke(ctx, SecurityGroups_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityGroupsClient) Signal(ctx context.Context, in *SecurityGroupsSignalRequest, opts ...grpc.CallOption) (*SecurityGroupsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityGroupsSignalResponse)
	err := c.cc.Invoke(ctx, SecurityGroups_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityGroupsServer is the server API for SecurityGroups service.
// All implementations must embed UnimplementedSecurityGroupsServer
// for forward compatibility.
type SecurityGroupsServer interface {
	// Retrieves the list of security groups.
	List(context.Context, *SecurityGroupsListRequest) (*SecurityGroupsListResponse, error)
	// Retrieves the details of one specific security group.
	Get(context.Context, *SecurityGroupsGetRequest) (*SecurityGroupsGetResponse, error)
	// Creates a new security group.
	Create(context.Context, *SecurityGroupsCreateRequest) (*SecurityGroupsCreateResponse, error)
	// Updates an existing security group.
	Update(context.Context, *SecurityGroupsUpdateRequest) (*SecurityGroupsUpdateResponse, error)
	// Deletes a security group.
	Delete(context.Context, *SecurityGroupsDeleteRequest) (*SecurityGroupsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *SecurityGroupsSignalRequest) (*SecurityGroupsSignalResponse, error)
	mustEmbedUnimplementedSecurityGroupsServer()
}

// UnimplementedSecurityGroupsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityGroupsServer struct{}

func (UnimplementedSecurityGroupsServer) List(context.Context, *SecurityGroupsListRequest) (*SecurityGroupsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSecurityGroupsServer) Get(context.Context, *SecurityGroupsGetRequest) (*SecurityGroupsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSecurityGroupsServer) Create(context.Context, *SecurityGroupsCreateRequest) (*SecurityGroupsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSecurityGroupsServer) Update(context.Context, *SecurityGroupsUpdateRequest) (*SecurityGroupsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSecurityGroupsServer) Delete(context.Context, *SecurityGroupsDeleteRequest) (*SecurityGroupsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSecurityGroupsServer) Signal(context.Context, *SecurityGroupsSignalRequest) (*SecurityGroupsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSecurityGroupsServer) mustEmbedUnimplementedSecurityGroupsServer() {}
func (UnimplementedSecurityGroupsServer) testEmbeddedByValue()                        {}

// UnsafeSecurityGroupsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityGroupsServer will
// result in compilation errors.
type UnsafeSecurityGroupsServer interface {
	mustEmbedUnimplementedSecurityGroupsServer()
}

func RegisterSecurityGroupsServer(s grpc.ServiceRegistrar, srv SecurityGroupsServer) {
	// If the following call pancis, it indicates UnimplementedSecurityGroupsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityGroups_ServiceDesc, srv)
}

func _SecurityGroups_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityGroupsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityGroupsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityGroups_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityGroupsServer).List(ctx, req.(*SecurityGroupsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityGroups_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityGroupsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityGroupsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityGroups_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityGroupsServer).Get(ctx, req.(*SecurityGroupsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityGroups_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityGroupsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityGroupsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityGroups_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityGroupsServer).Create(ctx, req.(*SecurityGroupsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityGroups_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityGroupsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityGroupsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityGroups_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityGroupsServer).Update(ctx, req.(*SecurityGroupsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityGroups_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityGroupsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityGroupsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityGroups_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityGroupsServer).Delete(ctx, req.(*SecurityGroupsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityGroups_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityGroupsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityGroupsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityGroups_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityGroupsServer).Signal(ctx, req.(*SecurityGroupsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityGroups_ServiceDesc is the grpc.ServiceDesc for SecurityGroups service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityGroups_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.SecurityGroups",
	HandlerType: (*SecurityGroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SecurityGroups_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SecurityGroups_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SecurityGroups_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SecurityGroups_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SecurityGroups_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _SecurityGroups_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/security_groups_service.proto",
}
