//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/subnets_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subnets_List_FullMethodName   = "/osac.private.v1.Subnets/List"
	Subnets_Get_FullMethodName    = "/osac.private.v1.Subnets/Get"
	Subnets_Create_FullMethodName = "/osac.private.v1.Subnets/Create"
	Subnets_Update_FullMethodName = "/osac.private.v1.Subnets/Update"
	Subnets_Delete_FullMethodName = "/osac.private.v1.Subnets/Delete"
	Subnets_Signal_FullMethodName = "/osac.private.v1.Subnets/Signal"
)

// SubnetsClient is the client API for Subnets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubnetsClient interface {
	// Retrieves the list of subnets.
	List(ctx context.Context, in *SubnetsListRequest, opts ...grpc.CallOption) (*SubnetsListResponse, error)
	// Retrieves the details of one specific subnet.
	Get(ctx context.Context, in *SubnetsGetRequest, opts ...grpc.CallOption) (*SubnetsGetResponse, error)
	// Creates a new subnet.
	Create(ctx context.Context, in *SubnetsCreateRequest, opts ...grpc.CallOption) (*SubnetsCreateResponse, error)
	// Updates an existing subnet.
	Update(ctx context.Context, in *SubnetsUpdateRequest, opts ...grpc.CallOption) (*SubnetsUpdateResponse, error)
	// Deletes a subnet.
	Delete(ctx context.Context, in *SubnetsDeleteRequest, opts ...grpc.CallOption) (*SubnetsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *SubnetsSignalRequest, opts ...grpc.CallOption) (*SubnetsSignalResponse, error)
}

type subnetsClient struct {
	cc grpc.ClientConnInterface
}

func NewSubnetsClient(cc grpc.ClientConnInterface) SubnetsClient {
	return &subnetsClient{cc}
}

func (c *subnetsClient) List(ctx context.Context, in *SubnetsListRequest, opts ...grpc.CallOption) (*SubnetsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubnetsListResponse)
	err := c.cc.Invoke(ctx, Subnets_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subnetsClient) Get(ctx context.Context, in *SubnetsGetRequest, opts ...grpc.CallOption) (*SubnetsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubnetsGetResponse)
	err := c.cc.Invoke(ctx, Subnets_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subnetsClient) Create(ctx context.Context, in *SubnetsCreateRequest, opts ...grpc.CallOption) (*SubnetsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubnetsCreateResponse)
	err := c.cc.Invoke(ctx, Subnets_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subnetsClient) Update(ctx context.Context, in *SubnetsUpdateRequest, opts ...grpc.CallOption) (*SubnetsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubnetsUpdateResponse)
	err := c.cc.Invoke(ctx, Subnets_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subnetsClient) Delete(ctx context.Context, in *SubnetsDeleteRequest, opts ...grpc.CallOption) (*SubnetsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubnetsDeleteResponse)
	err := c.cc.Invoke(ctx, Subnets_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subnetsClient) Signal(ctx context.Context, in *SubnetsSignalRequest, opts ...grpc.CallOption) (*SubnetsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubnetsSignalResponse)
	err := c.cc.Invoke(ctx, Subnets_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubnetsServer is the server API for Subnets service.
// All implementations must embed UnimplementedSubnetsServer
// for forward compatibility.
type SubnetsServer interface {
	// Retrieves the list of subnets.
	List(context.Context, *SubnetsListRequest) (*SubnetsListResponse, error)
	// Retrieves the details of one specific subnet.
	Get(context.Context, *SubnetsGetRequest) (*SubnetsGetResponse, error)
	// Creates a new subnet.
	Create(context.Context, *SubnetsCreateRequest) (*SubnetsCreateResponse, error)
	// Updates an existing subnet.
	Update(context.Context, *SubnetsUpdateRequest) (*SubnetsUpdateResponse, error)
	// Deletes a subnet.
	Delete(context.Context, *SubnetsDeleteRequest) (*SubnetsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *SubnetsSignalRequest) (*SubnetsSignalResponse, error)
	mustEmbedUnimplementedSubnetsServer()
}

// UnimplementedSubnetsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubnetsServer struct{}

func (UnimplementedSubnetsServer) List(context.Context, *SubnetsListRequest) (*SubnetsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSubnetsServer) Get(context.Context, *SubnetsGetRequest) (*SubnetsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSubnetsServer) Create(context.Context, *SubnetsCreateRequest) (*SubnetsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSubnetsServer) Update(context.Context, *SubnetsUpdateRequest) (*SubnetsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSubnetsServer) Delete(context.Context, *SubnetsDeleteRequest) (*SubnetsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSubnetsServer) Signal(context.Context, *SubnetsSignalRequest) (*SubnetsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSubnetsServer) mustEmbedUnimplementedSubnetsServer() {}
func (UnimplementedSubnetsServer) testEmbeddedByValue()                 {}

// UnsafeSubnetsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubnetsServer will
// result in compilation errors.
type UnsafeSubnetsServer interface {
	mustEmbedUnimplementedSubnetsServer()
}

func RegisterSubnetsServer(s grpc.ServiceRegistrar, srv SubnetsServer) {
	// If the following call pancis, it indicates UnimplementedSubnetsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subnets_ServiceDesc, srv)
}

func _Subnets_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubnetsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subnets_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubnetsServer).List(ctx, req.(*SubnetsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subnets_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubnetsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subnets_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubnetsServer).Get(ctx, req.(*SubnetsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subnets_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubnetsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subnets_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubnetsServer).Create(ctx, req.(*SubnetsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subnets_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubnetsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subnets_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubnetsServer).Update(ctx, req.(*SubnetsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subnets_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubnetsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subnets_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubnetsServer).Delete(ctx, req.(*SubnetsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subnets_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubnetsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subnets_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubnetsServer).Signal(ctx, req.(*SubnetsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Subnets_ServiceDesc is the grpc.ServiceDesc for Subnets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subnets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.Subnets",
	HandlerType: (*SubnetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Subnets_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Subnets_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Subnets_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Subnets_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Subnets_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _Subnets_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/subnets_service.proto",
}
