//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/virtual_networks_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VirtualNetworks_List_FullMethodName   = "/osac.private.v1.VirtualNetworks/List"
	VirtualNetworks_Get_FullMethodName    = "/osac.private.v1.VirtualNetworks/Get"
	VirtualNetworks_Create_FullMethodName = "/osac.private.v1.VirtualNetworks/Create"
	VirtualNetworks_Update_FullMethodName = "/osac.private.v1.VirtualNetworks/Update"
	VirtualNetworks_Delete_FullMethodName = "/osac.private.v1.VirtualNetworks/Delete"
	VirtualNetworks_Signal_FullMethodName = "/osac.private.v1.VirtualNetworks/Signal"
)

// VirtualNetworksClient is the client API for VirtualNetworks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirtualNetworksClient interface {
	// Retrieves the list of virtual networks.
	List(ctx context.Context, in *VirtualNetworksListRequest, opts ...grpc.CallOption) (*VirtualNetworksListResponse, error)
	// Retrieves the details of one specific virtual network.
	Get(ctx context.Context, in *VirtualNetworksGetRequest, opts ...grpc.CallOption) (*VirtualNetworksGetResponse, error)
	// Creates a new virtual network.
	Create(ctx context.Context, in *VirtualNetworksCreateRequest, opts ...grpc.CallOption) (*VirtualNetworksCreateResponse, error)
	// Updates an existing virtual network.
	Update(ctx context.Context, in *VirtualNetworksUpdateRequest, opts ...grpc.CallOption) (*VirtualNetworksUpdateResponse, error)
	// Deletes a virtual network.
	Delete(ctx context.Context, in *VirtualNetworksDeleteRequest, opts ...grpc.CallOption) (*VirtualNetworksDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *VirtualNetworksSignalRequest, opts ...grpc.CallOption) (*VirtualNetworksSignalResponse, error)
}

type virtualNetworksClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualNetworksClient(cc grpc.ClientConnInterface) VirtualNetworksClient {
	return &virtualNetworksClient{cc}
}

func (c *virtualNetworksClient) List(ctx context.Context, in *VirtualNetworksListRequest, opts ...grpc.CallOption) (*VirtualNetworksListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualNetworksListResponse)
	err := c.cc.Invoke(ctx, VirtualNetworks_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualNetworksClient) Get(ctx context.Context, in *VirtualNetworksGetRequest, opts ...grpc.CallOption) (*VirtualNetworksGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualNetworksGetResponse)
	err := c.cc.Invoke(ctx, VirtualNetworks_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualNetworksClient) Create(ctx context.Context, in *VirtualNetworksCreateRequest, opts ...grpc.CallOption) (*VirtualNetworksCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualNetworksCreateResponse)
	err := c.cc.Invoke(ctx, VirtualNetworks_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualNetworksClient) Update(ctx context.Context, in *VirtualNetworksUpdateRequest, opts ...grpc.CallOption) (*VirtualNetworksUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualNetworksUpdateResponse)
	err := c.cc.Invoke(ctx, VirtualNetworks_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualNetworksClient) Delete(ctx context.Context, in *VirtualNetworksDeleteRequest, opts ...grpc.CallOption) (*VirtualNetworksDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualNetworksDeleteResponse)
	err := c.cc.Invoke(ctx, VirtualNetworks_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualNetworksClient) Signal(ctx context.Context, in *VirtualNetworksSignalRequest, opts ...grpc.CallOption) (*VirtualNetworksSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualNetworksSignalResponse)
	err := c.cc.Invoke(ctx, VirtualNetworks_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualNetworksServer is the server API for VirtualNetworks service.
// All implementations must embed UnimplementedVirtualNetworksServer
// for forward compatibility.
type VirtualNetworksServer interface {
	// Retrieves the list of virtual networks.
	List(context.Context, *VirtualNetworksListRequest) (*VirtualNetworksListResponse, error)
	// Retrieves the details of one specific virtual network.
	Get(context.Context, *VirtualNetworksGetRequest) (*VirtualNetworksGetResponse, error)
	// Creates a new virtual network.
	Create(context.Context, *VirtualNetworksCreateRequest) (*VirtualNetworksCreateResponse, error)
	// Updates an existing virtual network.
	Update(context.Context, *VirtualNetworksUpdateRequest) (*VirtualNetworksUpdateResponse, error)
	// Deletes a virtual network.
	Delete(context.Context, *VirtualNetworksDeleteRequest) (*VirtualNetworksDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *VirtualNetworksSignalRequest) (*VirtualNetworksSignalResponse, error)
	mustEmbedUnimplementedVirtualNetworksServer()
}

// UnimplementedVirtualNetworksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVirtualNetworksServer struct{}

func (UnimplementedVirtualNetworksServer) List(context.Context, *VirtualNetworksListRequest) (*VirtualNetworksListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedVirtualNetworksServer) Get(context.Context, *VirtualNetworksGetRequest) (*VirtualNetworksGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVirtualNetworksServer) Create(context.Context, *VirtualNetworksCreateRequest) (*VirtualNetworksCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVirtualNetworksServer) Update(context.Context, *VirtualNetworksUpdateRequest) (*VirtualNetworksUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedVirtualNetworksServer) Delete(context.Context, *VirtualNetworksDeleteRequest) (*VirtualNetworksDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVirtualNetworksServer) Signal(context.Context, *VirtualNetworksSignalRequest) (*VirtualNetworksSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedVirtualNetworksServer) mustEmbedUnimplementedVirtualNetworksServer() {}
func (UnimplementedVirtualNetworksServer) testEmbeddedByValue()                         {}

// UnsafeVirtualNetworksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtualNetworksServer will
// result in compilation errors.
type UnsafeVirtualNetworksServer interface {
	mustEmbedUnimplementedVirtualNetworksServer()
}

func RegisterVirtualNetworksServer(s grpc.ServiceRegistrar, srv VirtualNetworksServer) {
	// If the following call pancis, it indicates UnimplementedVirtualNetworksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VirtualNetworks_ServiceDesc, srv)
}

func _VirtualNetworks_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualNetworksListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualNetworksServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualNetworks_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualNetworksServer).List(ctx, req.(*VirtualNetworksListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualNetworks_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualNetworksGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualNetworksServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualNetworks_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualNetworksServer).Get(ctx, req.(*VirtualNetworksGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualNetworks_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualNetworksCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualNetworksServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualNetworks_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualNetworksServer).Create(ctx, req.(*VirtualNetworksCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualNetworks_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualNetworksUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualNetworksServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualNetworks_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualNetworksServer).Update(ctx, req.(*VirtualNetworksUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualNetworks_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualNetworksDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualNetworksServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualNetworks_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualNetworksServer).Delete(ctx, req.(*VirtualNetworksDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualNetworks_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualNetworksSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualNetworksServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualNetworks_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualNetworksServer).Signal(ctx, req.(*VirtualNetworksSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VirtualNetworks_ServiceDesc is the grpc.ServiceDesc for VirtualNetworks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtualNetworks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.VirtualNetworks",
	HandlerType: (*VirtualNetworksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _VirtualNetworks_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _VirtualNetworks_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _VirtualNetworks_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _VirtualNetworks_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VirtualNetworks_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _VirtualNetworks_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/virtual_networks_service.proto",
}
